// flow-typed signature: 2f47cce8c922deb88956d21e7acac3d6
// flow-typed version: <<STUB>>/conventional-github-releaser_v^1.1.12/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conventional-github-releaser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'conventional-github-releaser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'conventional-github-releaser/src/cli' {
  declare module.exports: any;
}

declare module 'conventional-github-releaser/src/index' {
  declare module.exports: any;
}

declare module 'conventional-github-releaser/src/transform' {
  declare module.exports: any;
}

declare module 'conventional-github-releaser/src/transform.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'conventional-github-releaser/src/cli.js' {
  declare module.exports: $Exports<'conventional-github-releaser/src/cli'>;
}
declare module 'conventional-github-releaser/src/index.js' {
  declare module.exports: $Exports<'conventional-github-releaser/src/index'>;
}
declare module 'conventional-github-releaser/src/transform.js' {
  declare module.exports: $Exports<'conventional-github-releaser/src/transform'>;
}
declare module 'conventional-github-releaser/src/transform.spec.js' {
  declare module.exports: $Exports<'conventional-github-releaser/src/transform.spec'>;
}
